FROM jenkins/jenkins:lts-jdk21

# root 권한으로 전환
USER root

# docker-ce-cli 설치
RUN apt-get update && \
    apt-get install -y docker.io

RUN apt-get install -y curl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# jenkins 사용자로 복귀
USER jenkins