apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: NodePort # 외부에서 접근 가능하도록 NodePort 타입 사용
  ports:
    - port: 8080 # 서비스가 노출할 포트
      targetPort: 8080 # 젠킨스 컨테이너의 UI 포트
      nodePort: 32000 # 30000-32767 범위 내의 사용 가능한 포트 (외부 접근용)
      name: http
    - port: 50000 # Jenkins Agent 연결 포트
      targetPort: 50000
      name: jnlp