apiVersion: v1
kind: Service
metadata:
  name: backend-service # 이 서비스 이름으로 클러스터 내부에서 접근 가능
  labels:
    app: backend
spec:
  selector:
    app: backend # 이 라벨을 가진 파드들을 서비스가 트래픽을 보낼 대상으로 선택
  ports:
    - protocol: TCP
      port: 80 # 쿠버네티스 서비스가 노출할 포트
      targetPort: 8080 # 파드(컨테이너)의 실제 포트
      nodePort: 30008 # NodePort로 노출할 포트
  type: NodePort