apiVersion: v1
kind: Service
metadata:
  name: mysql # 이 서비스 이름이 백엔드에서 사용할 DNS 이름이 됩니다 (예: jdbc:mysql://mysql:3306/...)
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None # Headless Service (파드 IP로 직접 연결, StatefulSet에 주로 사용)
                  # 또는 일반 ClusterIP: type: ClusterIP