# 1. MySQL 데이터 저장을 위한 PVC (Persistent Volume Claim)
#    클러스터에 Dynamic Provisioner가 설정되어 있어야 합니다.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce # 하나의 Pod만 PVC에 접근 가능
  resources:
    requests:
      storage: 1Gi # 필요한 스토리지 용량 (개발용으로 작게 설정)